# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('has_comment', models.BooleanField(default=False)),
                ('Blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_Post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Paragraph_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Paragraph'),
        ),
    ]
